service: kamal_exemple

image: bizzon31/kamal_exemple

servers:
    - 77.51.218.207

ssh:
  user: bizzon

registry:
  username: bizzon31

  password: Pasport313@

env:
  secret:
    - RAILS_MASTER_KEY
    - HELLO
    - SECRET_KEY_BASE

volumes:
  - "storage:/rails/storage"

builder:
  arch: amd64
