<% require "dotenv"; Dotenv.load(".env.rb") %>
service: kamal_exemple

image: bizzon31/kamal_exemple

servers:
  web:
    - 77.51.218.207

ssh:
  user: bizzon

registry:
  username: bizzon31

  password: #Pasport313@
    - KAMAL_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST: 77.51.218.207
  secret:
    - RAILS_MASTER_KEY
    - HELLO
    # - SECRET_KEY_BASE

volumes:
  - "storage:/rails/storage"

builder:
  arch: amd64
